### ISSUE TITLE
question about your documentation tool(s)

### ISSUE THREAD

**Issue by MareoRaft** [jankapunkt/js-set-extension#2]
By the way, I see you have docstrings like

    /**
     * Adds a value to the set. If the set already contains the value, nothing happens.
     * Overrides Set.prototype.add.
     * @name Set.prototype.add
     * @function
     * @throws Error if rules function exists and {value} failed the rules check.
     * @param value {*}- Required. Any arbitrary value to be added to the set.
     * @returns {Set} the Set object
     * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/add
     */

in your code.  Is there a specific tool you use to generate these?  And is there a tool that produces documentation from these comments?  I'm considering using this as I grow my JavaScript skills.  I lack good documentation tools.  Any recommendations are appreciated!

P.S.  Let me know if you'd prefer me not posting off-topic questions such as these, or if you prefer I send them to a different place.

**Comment by jankapunkt** [comment]
Yes, it is [jsdoc](http://usejsdoc.org/) and you can play around with it in this package, because it is installed within the [devDependencies](https://github.com/jankapunkt/js-set-extension/blob/master/package/package.json) and you can use it via the scripts using

```bash
npm run docs
```

You can also see how it is currently generates inside the `docs` folder or on https://jankapunkt.github.io/js-set-extension/Set.html

**Comment by MareoRaft** [comment]
Thanks!  Good to know!
